window.AdminService={
 db(){const db=StoreDB.getClient();if(!db)throw new Error('Supabase não configurado.');return db},
 async dashboard(){const db=this.db(),today=new Date(),month=new Date();today.setHours(0,0,0,0);month.setDate(1);month.setHours(0,0,0,0);const[orders,customers,products,stock]=await Promise.all([db.from('orders').select('id,order_number,status,grand_total,created_at,customers(company_name,contact_name)').order('created_at',{ascending:false}).limit(1000),db.from('customers').select('id',{count:'exact',head:true}),db.from('products').select('id',{count:'exact',head:true}),db.from('stock').select('quantity_on_hand,quantity_reserved,min_stock')]);for(const r of[orders,customers,products,stock])if(r.error)throw r.error;const rows=orders.data||[],valid=o=>!['cancelled','canceled','expired'].includes(String(o.status||'').toLowerCase()),sum=d=>rows.filter(o=>new Date(o.created_at)>=d&&valid(o)).reduce((s,o)=>s+Number(o.grand_total||0),0),st=stock.data||[];return{salesToday:sum(today),salesMonth:sum(month),orders:rows.length,customers:customers.count||0,products:products.count||0,outOfStock:st.filter(x=>(x.quantity_on_hand-x.quantity_reserved)<=0).length,lowStock:st.filter(x=>(x.quantity_on_hand-x.quantity_reserved)>0&&(x.quantity_on_hand-x.quantity_reserved)<=x.min_stock).length,recent:rows.slice(0,8)}},
 async products(search=''){let q=this.db().from('products').select('id,sku,manufacturer_ref,ean,name,is_active,is_new,is_promo,brands(name),categories(name),product_prices(cost_price,pricing_method,margin_percent,fixed_sale_price),stock(quantity_on_hand,quantity_reserved,min_stock)').order('created_at',{ascending:false}).limit(250);if(search){const s=search.replaceAll(',',' ');q=q.or(`name.ilike.%${s}%,sku.ilike.%${s}%,manufacturer_ref.ilike.%${s}%,ean.ilike.%${s}%`)}const{data,error}=await q;if(error)throw error;return data||[]},
 async stock(search=''){let q=this.db().from('stock').select('id,product_id,quantity_on_hand,quantity_reserved,min_stock,warehouse,updated_at,products(sku,manufacturer_ref,name,brands(name))').order('updated_at',{ascending:false}).limit(500);const{data,error}=await q;if(error)throw error;const s=search.toLowerCase();return(data||[]).filter(x=>!s||[x.products?.sku,x.products?.manufacturer_ref,x.products?.name,x.products?.brands?.name].some(v=>String(v||'').toLowerCase().includes(s)))},
 async stockMovements(){const{data,error}=await this.db().from('stock_movements').select('id,movement_type,quantity,note,created_at,products(sku,manufacturer_ref,name),profiles(full_name)').order('created_at',{ascending:false}).limit(250);if(error)throw error;return data||[]},
 async suppliers(){const{data,error}=await this.db().from('suppliers').select('*').order('name').limit(500);if(error)throw error;return data||[]},
 async orders(){const{data,error}=await this.db().from('orders').select('id,order_number,status,payment_status,payment_method,grand_total,created_at,customers(company_name,contact_name,email)').order('created_at',{ascending:false}).limit(500);if(error)throw error;return data||[]},
 async orderDetail(id){const db=this.db();const[o,h]=await Promise.all([db.from('orders').select('*,customers(company_name,contact_name,email,phone,vat_number),order_items(*,products(name,sku,manufacturer_ref))').eq('id',id).single(),db.from('order_status_history').select('*').eq('order_id',id).order('created_at',{ascending:false})]);if(o.error)throw o.error;if(h.error)throw h.error;return{order:o.data,history:h.data||[]}},
 async customers(){const{data,error}=await this.db().from('customers').select('id,company_name,contact_name,vat_number,email,phone,status,general_discount_percent,credit_limit,created_at,customer_groups(name)').order('created_at',{ascending:false}).limit(500);if(error)throw error;return data||[]},
 async lookups(){const db=this.db(),[b,c,s]=await Promise.all([db.from('brands').select('id,name').order('name'),db.from('categories').select('id,name').order('name'),db.from('suppliers').select('id,name').order('name')]);for(const x of[b,c,s])if(x.error)throw x.error;return{brands:b.data||[],categories:c.data||[],suppliers:s.data||[]}},
 async product(id){const{data,error}=await this.db().from('products').select('*,product_prices(*),stock(*),product_images(*)').eq('id',id).single();if(error)throw error;return data},
 async saveProduct(v,id=null){const db=this.db(),{data:{user}}=await db.auth.getUser(),slug=(v.slug||v.name||'produto').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');const p={sku:v.sku,manufacturer_ref:v.manufacturer_ref||null,ean:v.ean||null,name:v.name,slug,brand_id:v.brand_id||null,category_id:v.category_id||null,primary_supplier_id:v.primary_supplier_id||null,short_description:v.short_description||null,full_description:v.full_description||null,is_active:!!v.is_active,is_featured:!!v.is_featured,is_new:!!v.is_new,is_promo:!!v.is_promo,updated_at:new Date().toISOString()};let r=id?await db.from('products').update(p).eq('id',id).select().single():await db.from('products').insert({...p,created_by:user?.id||null}).select().single();if(r.error)throw r.error;const pid=r.data.id,margin=Number(v.margin_percent||0),cost=Number(v.cost_price||0),supplierPvp=Number(v.supplier_pvp||0),calculated=margin?cost/(1-margin/100):supplierPvp;let x=await db.from('product_prices').upsert({product_id:pid,cost_price:cost,pricing_method:v.price_source||'margin',margin_percent:margin||null,fixed_sale_price:v.price_source==='supplier_pvp'?supplierPvp:calculated,updated_by:user?.id||null},{onConflict:'product_id'});if(x.error)throw x.error;x=await db.from('stock').upsert({product_id:pid,quantity_on_hand:Number(v.quantity_on_hand||0),quantity_reserved:Number(v.quantity_reserved||0),min_stock:Number(v.min_stock||0),warehouse:'Principal'},{onConflict:'product_id'});if(x.error)throw x.error;if(v.image_url){x=await db.from('product_images').upsert({product_id:pid,url:v.image_url,alt_text:v.name,sort_order:0,is_primary:true},{onConflict:'product_id,url'});if(x.error)throw x.error}return r.data},
 async previewSupplierCsv(url,delimiter=';'){const{data,error}=await this.db().functions.invoke('supplier-csv-preview',{body:{url,delimiter,limit:100}});if(error)throw error;if(data?.error)throw new Error(data.error);return data},
 async importSupplierCsv(url,delimiter,mapping,options){const{data,error}=await this.db().functions.invoke('supplier-csv-import',{body:{url,delimiter,mapping,options}});if(error)throw error;if(data?.error)throw new Error(data.error);return data}
};